### ISSUE TITLE
imgui could not load font file

### ISSUE THREAD

**Issue by jonathan-sung** [hadryansalles/Luz#29]
hi, i just successfully compiled the project, but for some reason when i run ./Luz, it gives me the following error:
```
/Luz/deps/imgui/imgui_draw.cpp:2254: ImFont* ImFontAtlas::AddFontFromFileTTF(const char*, float, const ImFontConfig*, const ImWchar*): Assertion `(0) && "Could not load font file!"' failed.
```
i don't know what to do 🤷‍♂️
please help! 🙆‍♂️

**Comment by The3dVehicleguy** [comment]
> hi, i just successfully compiled the project, but for some reason when i run ./Luz, it gives me the following error:
> 
> ```
> /Luz/deps/imgui/imgui_draw.cpp:2254: ImFont* ImFontAtlas::AddFontFromFileTTF(const char*, float, const ImFontConfig*, const ImWchar*): Assertion `(0) && "Could not load font file!"' failed.
> ```
> 
> i don't know what to do 🤷‍♂️ please help! 🙆‍♂️

You need to take the `assets` folder and copy and paste it into the bin folder with the Luz.exe

**Comment by hadryansalles** [comment]
hey @jonathan-sung @The3dVehicleguy thanks for reporting this issue

I updated [README](https://github.com/hadryansalles/Luz?tab=readme-ov-file#build-and-run) with new instruction to build/run on linux, but in short: to execute on linux you are supposed to run from main directory:
```
./bin/Luz
```
that's because the paths to assets and everything else are relative to the main directory

The default scene also had another issue, so please, pull the latest main branch to have it working (#31)

If you guys have any other issue, I'm glad to help

**Comment by jonathan-sung** [comment]
> hey @jonathan-sung @The3dVehicleguy thanks for reporting this issue
> 
> I updated [README](https://github.com/hadryansalles/Luz?tab=readme-ov-file#build-and-run) with new instruction to build/run on linux, but in short: to execute on linux you are supposed to run from main directory:
> 
> ```
> ./bin/Luz
> ```
> 
> that's because the paths to assets and everything else are relative to the main directory
> 
> The default scene also had another issue, so please, pull the latest main branch to have it working (#31)
> 
> If you guys have any other issue, I'm glad to help

i'm sorry, but im afraid it's still not working. i get a: `Segmentation fault (core dumped)` error

**Comment by hadryansalles** [comment]
hey, checkout latest main, should be fixed now
